# Generated by Django 4.1.3 on 2022-12-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0002_remove_track_album_remove_track_artists_delete_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('album_type', models.CharField(blank=True, max_length=100)),
                ('spotify_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('release_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist_type', models.CharField(blank=True, max_length=100)),
                ('spotify_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spotify_url', models.URLField(blank=True)),
                ('preview_url', models.URLField(blank=True)),
                ('explicit_content', models.BooleanField(default=False)),
                ('duration', models.IntegerField(max_length=99999999, null=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.album')),
                ('artists', models.ManyToManyField(to='music.artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='music.artist'),
        ),
    ]
