# Generated by Django 4.1.3 on 2022-12-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_track_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_url_big',
            field=models.URLField(blank=True),
        ),
    ]
