# Generated by Django 4.1.3 on 2022-12-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_image_url_big'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='spotify_url',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='spotify_url',
        ),
        migrations.RemoveField(
            model_name='track',
            name='spotify_url',
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.URLField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.URLField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
