# Generated by Django 4.1.3 on 2022-12-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_album_spotify_url_remove_artist_spotify_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
