# Generated by Django 4.1.3 on 2022-12-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='image_url_big',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='spotify_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
