# Generated by Django 4.1.3 on 2022-12-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_album_album_type_alter_album_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='playlist',
            field=models.ManyToManyField(to='music.playlist'),
        ),
    ]
