# Generated by Django 4.1.3 on 2022-12-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_playlist_track_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='spotify_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
