# Generated by Django 4.1.3 on 2022-12-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_playlist_spotify_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
