# Generated by Django 4.1.5 on 2023-01-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='id',
        ),
        migrations.AlterField(
            model_name='meme',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='meme',
            name='volume',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
