# Generated by Django 4.1.5 on 2023-01-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_meme_id_alter_meme_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
