# Generated by Django 4.1.5 on 2023-01-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_meme_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meme',
        ),
    ]
