# Generated by Django 4.1.5 on 2023-01-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('volume', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
    ]
