# Generated by Django 4.1.5 on 2023-01-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
