# Generated by Django 4.1.3 on 2022-12-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game_bio', models.TextField(max_length=1000)),
                ('my_description', models.TextField(max_length=2000)),
                ('favourite', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('developed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.developer')),
                ('genre', models.ManyToManyField(to='games.genre')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.publisher')),
            ],
        ),
    ]
