# Generated by Django 4.1.4 on 2022-12-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image_url',
            new_name='cover_url',
        ),
    ]
