# Generated by Django 4.1.3 on 2022-12-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(null=True, to='games.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='my_description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
