# Generated by Django 4.1.4 on 2023-01-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_screenshot_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='abs_favourite',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='want',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='favourite',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
