# Generated by Django 4.1.3 on 2022-12-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='my_description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
