# Generated by Django 4.1.3 on 2022-12-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_my_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='my_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
